defaults:
  - optimizer: SGD
  - _self_

model: resnet18
seed: 42
device: cuda:0
num_workers: 4

train:
  epochs: 10
  dataset:
    train:
      path: data/cats_dogs/train_11k
      batch_size: 32
    val:
      path: data/cats_dogs/val
      batch_size: 32
    test:
      path: data/cats_dogs/test_labeled
      batch_size: 32
  save_path: data/ckpt

infer:
  ckpt: data/ckpt/resnet18.onnx
  img: data/cats_dogs/test_labeled/cat/cat.5.jpg

transform:
  h: 96
  w: 96
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
